template: true   # required for local templates
valuesFilePath: ./values.yml

resources:
  # Sample Go app in a GitRepo
  - name: go_repo
    type: GitRepo
    configuration:
      path: {{ .Values.repoPath }}
      branches:
        include: main
      gitProvider: {{ .Values.gitProvider }}

  # # Build info for the published Go module
  # - name: go_build_info_publish_module
  #   type: BuildInfo
  #   configuration:
  #     sourceArtifactory: {{ .Values.artifactory }}

  # Build info for the published Go app
  - name: go_buildinfo
    type: BuildInfo
    configuration:
      sourceArtifactory: {{ .Values.artifactory }}


pipelines:
  - name: go_build_pipeline_example
    steps:
      # Build the Go sample app from the GitRepo
      - name: build_go
        type: GoBuild
        configuration:
          sourceLocation: .
          resolverRepo: go-virtual
          # outputLocation: /tmp/dist
          # outputFile: hello_gb
          noRegistry: true
          inputResources:
            - name: go_repo
          integrations:
            - name: {{ .Values.artifactory }}

      # Publish the Go sample app binary to Artifactory
      - name: publish_go_binary
        type: GoPublishBinary
        configuration:
          inputSteps:
            - name: build_go
          targetRepository: go-local
          integrations:
            - name: {{ .Values.artifactory }}

      # Publish the Go sample app build info
      - name: publish_build
        type: PublishBuildInfo
        configuration:
          inputSteps:
            - name: publish_go_binary
          outputResources:
            - name: go_buildinfo

      # # Publish the Go module from the GitRepo
      # - name: publish_go_module
      #   type: GoPublishModule
      #   configuration:
      #     environmentVariables:
      #       JFROG_CLI_BUILD_NAME: go_example_module_publish
      #     sourceLocation: .
      #     version: v0.0.0
      #     targetRepository: myrepo-go
      #     autoPublishBuildInfo: true
      #     integrations:
      #       - name: myArtifactory
      #     inputResources:
      #       - name: go_example
      #     outputResources:
      #       - name: go_build_info_publish_module
